<?xml version='1.0'?>

<robot name="run_2" xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:include filename="$(find mk_2)/gazebo/property.gazebo"/>
	<!--criterion-->
	<xacro:property name="PI" value="3.141592"/>
	<!--//////////base properties//////////-->
	<xacro:property name="base_x" value="0.3"/>
	<xacro:property name="base_y" value="0.23"/>
	<xacro:property name="base_z" value="0.1"/>
	<xacro:property name="base_m" value="2.0"/>
	<!--//////////suspension properties//////////-->
	<xacro:property name="suspension_x" value="0.06"/>
	<xacro:property name="suspension_y" value="0.03"/>
	<xacro:property name="suspension_z" value="0.04"/>
	<xacro:property name="suspension_m" value="0.063"/>
	<!--//////////actuator properties//////////-->
	<xacro:property name="actuator_x" value="0.061"/>
	<xacro:property name="actuator_y" value="0.0405"/>
	<xacro:property name="actuator_z" value="0.0455"/>
	<xacro:property name="actuator_m" value="0.1276"/>
	<!--//////////wheel properties//////////-->
	<xacro:property name="wheel_w" value="0.03"/>
	<xacro:property name="wheel_d" value="0.1"/>
	<xacro:property name="wheel_m" value="0.14"/>

	<!--//////////BASE//////////-->
	<link name="base">
		<collision>
			<origin xyz="0 0 0.21025" rpy="0 0 0"/>
			<geometry>
				<box size="0.3 0.23 0.155"/>
				<!--mesh filename="package://mk_2/mesh/"-->
			</geometry>
		</collision>
		
		<visual>
			<origin xyz="0 0 0.21025" rpy="0 0 0"/>
			<geometry>
				<!--box size="0.3 0.23 0.155"/-->
				<mesh filename="package://mk_2/mesh/base.dae"/>
			</geometry>
		</visual>
		
		<inertial>
			<origin xyz="0 0 0.21025" rpy="0 0 0"/>
			<mass value="${base_m}"/>
			<inertia ixx="${base_m / 12.0 * (base_y * base_y + base_z * base_z)}" ixy="0" ixz="0"
						iyy="${base_m / 12.0 * (base_z * base_z + base_x * base_x)}" iyz="0"
						izz="${base_m / 12.0 * (base_x * base_x + base_y * base_y)}"/>
		</inertial>
	</link>
	
	<!--//////////BALLCOLLECTOR//////////-->
	<link name="ballcollector">
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://mk_2/mesh/ballcollector.dae"/>
			</geometry>
		</collision>
		
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<!--box size="0.3 0.23 0.155"/-->
				<mesh filename="package://mk_2/mesh/ballcollector.dae"/>
			</geometry>
		</visual>
		
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<mass value="0.2"/>
			<inertia ixx="${0.2 / 12.0 * (base_y * base_y + base_z * base_z)}" ixy="0" ixz="0"
						iyy="${0.2 / 12.0 * (base_z * base_z + base_x * base_x)}" iyz="0"
						izz="${0.2 / 12.0 * (base_x * base_x + base_y * base_y)}"/>
		</inertial>
	</link>
	<joint name="collector" type="fixed">
		<origin xyz="0.15 0 0.17525" rpy="0 0 0"/>
		<parent link="base"/>
		<child link="ballcollector"/>
	</joint>
	<!--//////////SUSPENSION//////////-->
	<xacro:macro name="suspension" params="prefix *direction *structure *joint">
		<link name="${prefix}_suspension">
			
		
			<visual>
				<xacro:insert_block name="structure"/>
				<geometry>
					<mesh filename="package://mk_2/mesh/upsuspension.dae"/>
				</geometry>
			</visual>
		
			<inertial>
				<xacro:insert_block name="direction"/>
				<!--origin xyz="0 0.015 0" rpy="0 0 0"/-->
				<mass value="${suspension_m}"/>
				<inertia ixx="${suspension_m / 12.0 * (suspension_y * suspension_y + suspension_z * suspension_z)}" ixy="0" ixz="0"
							iyy="${suspension_m / 12.0 * (suspension_z * suspension_z + suspension_x * suspension_x)}" iyz="0"
							izz="${suspension_m / 12.0 * (suspension_x * suspension_x + suspension_y * suspension_y)}"/>
			</inertial>
		</link>
		
		<joint name="${prefix}_Sjoint" type="fixed">
			<xacro:insert_block name="joint"/>
			<parent link="base"/>
			<child link="${prefix}_suspension"/>
		</joint>
	</xacro:macro>
	
	<xacro:suspension prefix="FL">
		<origin xyz="0 0.015 0" rpy="0 0 0"/>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<origin xyz="0.100 0.115 0.14275" rpy="0 0 0"/>
	</xacro:suspension>
	<xacro:suspension prefix="FR">
		<origin xyz="0 -0.015 0" rpy="0 0 0"/>
		<origin xyz="0 0 0" rpy="0 0 ${PI}"/>
		<origin xyz="0.100 -0.115 0.14275" rpy="0 0 0"/>
	</xacro:suspension>
	<xacro:suspension prefix="BL">
		<origin xyz="0 0.015 0" rpy="0 0 0"/>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<origin xyz="-0.100 0.115 0.14275" rpy="0 0 0"/>
	</xacro:suspension>
	<xacro:suspension prefix="BR">
		<origin xyz="0 -0.015 0" rpy="0 0 0"/>
		<origin xyz="0 0 0" rpy="0 0 ${PI}"/>
		<origin xyz="-0.100 -0.115 0.14275" rpy="0 0 0"/>
	</xacro:suspension>
	<!--//////////ACTUATORS & WHEELS//////////-->
	<xacro:macro name="actwheel" params="prefix *structure *meshmesh *joint *wjoint">
		<link name="${prefix}_actuator">
			<collision>
				<origin xyz="0 0 -0.02275" rpy="0 0 0"/>
				<geometry>
					<box size="0.061 0.0405 0.0455"/>
					<!--mesh filename="package://mk_2/mesh/"/-->
				</geometry>
			</collision>
		
			<visual>
				<xacro:insert_block name="structure"/>
				<geometry>
					<xacro:insert_block name="meshmesh"/>
					<!--mesh filename="package://mk_2/mesh/upsuspension.dae"/-->
				</geometry>
			</visual>
		
			<inertial>
				<origin xyz="0 0 -0.02275" rpy="0 0 0"/>
				<!--origin xyz="0 0.015 0" rpy="0 0 0"/-->
				<mass value="${actuator_m}"/>
				<inertia ixx="${actuator_m / 12.0 * (actuator_y * actuator_y + actuator_z * actuator_z)}" ixy="0" ixz="0"
							iyy="${actuator_m / 12.0 * (actuator_z * actuator_z + actuator_x * actuator_x)}" iyz="0"
							izz="${actuator_m / 12.0 * (actuator_x * actuator_x + actuator_y * actuator_y)}"/>
			</inertial>
		</link>
		
		<joint name="${prefix}_Ajoint" type="prismatic">
			<xacro:insert_block name="joint"/>
			<parent link="base"/>
			<child link="${prefix}_actuator"/>
			<axis xyz="0 0 1"/>
			<limit effort="1000.0" velocity="1000.0" upper="0.000" lower="-0.040"/>
		</joint>
		
		<link name="${prefix}_wheel">
			<collision>
				<origin xyz="0 0 0" rpy="${PI/2.0} 0 0"/>
				<geometry>
					<cylinder radius="${wheel_d / 2.0}" length="${wheel_w}"/>
					<!--mesh filename="package://mk_2/mesh/"/-->
				</geometry>
			</collision>
		
			<visual>
				<xacro:insert_block name="structure"/>
				<geometry>
					<mesh filename="package://mk_2/mesh/wheel.dae"/>
				</geometry>
			</visual>
		
			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<!--origin xyz="0 0.015 0" rpy="0 0 0"/-->
				<mass value="${wheel_m}"/>
				<inertia ixx="${wheel_m / 12.0 * (3.0 / 4.0 * (wheel_d) * (wheel_d) + (wheel_w) * (wheel_w))}" ixy="0" ixz="0"
							iyy="${wheel_m / 2.0 * (wheel_d / 2.0) * (wheel_d / 2.0)}" iyz="0" 
							izz="${wheel_m / 12.0 * (3.0 / 4.0 * (wheel_d) * (wheel_d) + (wheel_w) * (wheel_w))}" />
			</inertial>
		</link>
			
		<joint name="${prefix}_Wjoint" type="continuous">
			<xacro:insert_block name="wjoint"/>
			<parent link="${prefix}_actuator"/>
			<child link="${prefix}_wheel"/>
			<axis xyz="0 1 0"/>
		</joint>
		
		<transmission name="suspension_${prefix}_transmission">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="${prefix}_Ajoint">
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			</joint>
			<actuator name="${prefix}_Amotor">
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
		</transmission>
		
		<transmission name="actuator_${prefix}_transmission">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="${prefix}_Wjoint">
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			</joint>
			<actuator name="${prefix}_Wmotor">
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
		</transmission>
	</xacro:macro>
	
	<xacro:actwheel prefix="FL">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<mesh filename="package://mk_2/mesh/actuator.dae"/>
		<origin xyz="0.100 0.135 0.11275" rpy="0 0 0"/>
		<origin xyz="0.006293 ${(0.02025 + (wheel_w/2.0))} -0.02275" rpy="0 0 0"/>
	</xacro:actwheel>
	<xacro:actwheel prefix="FR">
		<origin xyz="0 0 0" rpy="0 0 ${PI}"/>
		<mesh filename="package://mk_2/mesh/actuator_2.dae"/>
		<origin xyz="0.100 -0.135 0.11275" rpy="0 0 0"/>
		<origin xyz="0.006293 ${-(0.02025 + (wheel_w/2.0))} -0.02275" rpy="0 0 0"/>
	</xacro:actwheel>
	<xacro:actwheel prefix="BL">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<mesh filename="package://mk_2/mesh/actuator_2.dae"/>
		<origin xyz="-0.100 0.135 0.11275" rpy="0 0 0"/>
		<origin xyz="-0.006293 ${(0.02025 + (wheel_w/2.0))} -0.02275" rpy="0 0 0"/>
	</xacro:actwheel>
	<xacro:actwheel prefix="BR">
		<origin xyz="0 0 0" rpy="0 0 ${PI}"/>
		<mesh filename="package://mk_2/mesh/actuator.dae"/>
		<origin xyz="-0.100 -0.135 0.11275" rpy="0 0 0"/>
		<origin xyz="-0.006293 ${-(0.02025 + (wheel_w/2.0))} -0.02275" rpy="0 0 0"/>
	</xacro:actwheel>
	<!--put run_2 into gazebo space-->
	<gazebo>
		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotNamespace>/run_2</robotNamespace>
			<robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
		</plugin>
	</gazebo>
</robot>